channels = ['#slothtests']
bot_nick = "Alison|Tasty"
triggers = [':', 'hax dis: ', 'ur mom ']
whitelist = []
dev = True
location = "oslo"
outputredir = True
get_hash = True
ignorelist = []
ignorelist_set = False
end_triggers = [' ', '', ',', ':', '|']
whitelist_set = False
midsentence_comment = True
operators = ['Sloth']
outputredir_all = False
midsentence_trigger = False
autoweather = True
autoweather_time = 1149