whitelist = []
ignorelist = []
ignorelist_set = False
end_triggers = [' ', '', ',', ':', '|']
whitelist_set = False
outputredir_all = False
midsentence_trigger = False
channels = ['#slothtests']
bot_nick = "Alison|Tasty"
triggers = [':', 'hax dis: ', 'ur mom ']
outputredir = True
get_hash = True
dev = False
midsentence_comment = True
operators = ['Sloth']
